ToDoAspNetMvc/Controllers/ToDoListsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using ToDoListLibrary;

namespace ToDoAspNetMvc.Controllers;

public class ToDoListsController : Controller
{
    private readonly ApplicationContext _context;

    public ToDoListsController(ApplicationContext context)
    {
        _context = context;
    }

    // GET: ToDoLists
    public async Task<IActionResult> Index()
    {
        return View(await _context.Lists
            .Include(l => l.EntryList)
            .ToListAsync());
    }

    // GET: ToDoLists/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists
            .Include(l => l.EntryList)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoList == null)
        {
            return NotFound();
        }

        return View(toDoList);
    }

    // GET: ToDoLists/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: ToDoLists/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Title,Hide")] ToDoList toDoList)
    {
        if (ModelState.IsValid)
        {
            _context.Add(toDoList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(toDoList);
    }

    // GET: ToDoLists/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists.FindAsync(id);
        if (toDoList == null)
        {
            return NotFound();
        }
        return View(toDoList);
    }

    // POST: ToDoLists/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Hide")] ToDoList toDoList)
    {
        if (id != toDoList.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(toDoList);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ToDoListExists(toDoList.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(toDoList);
    }

    // GET: ToDoLists/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoList == null)
        {
            return NotFound();
        }

        return View(toDoList);
    }

    // POST: ToDoLists/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var toDoList = await _context.Lists.FindAsync(id);
        _context.Lists.Remove(toDoList);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool ToDoListExists(int id)
    {
        return _context.Lists.Any(e => e.Id == id);
    }
}

ToDoAspNetMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/ToDoAspNetMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ToDoLists" asp-action="Index">My Lists</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-default btn-lg" asp-area="" asp-controller="Home" asp-action="Index">
                                <span class="bi bi-house"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2024 - Capstone
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/customFields.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoAspNetMvc/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

ToDoAspNetMvc/Views/Shared/_ToDoEntryDetails.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@using ToDoListLibrary
@model ToDoEntryViewModel

@{
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<div class="form-group">
    <label asp-for="Title" class="control-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label"></label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="DueDate" class="control-label"></label>
    <input asp-for="DueDate" class="form-control" />
    <span asp-validation-for="DueDate" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Completed" class="control-label"></label>
    <select asp-for="Completed" asp-items="Html.GetEnumSelectList<Status>()" class="form-control"></select>
</div>
<div id="CustomFields">
    @{
        if (Model != null)
        {
            @for (var i = 0; i < Model.Fields.Count; i++)
            {
                <div class="form-group field_form" id="Field_@Model.Fields[i].Id">
                    <input type="hidden" asp-for="Fields[i].Id" />
                    <div style="display: flex">
                        <input asp-for="Fields[i].Name" class="control-label" />
                        <a class="btn btn-sm DeleteField" data-toggle="tooltip" title="Delete field" data-fieldid="@Model.Fields[i].Id" data-fieldtoken="@requestToken" onclick="deleteField(this)">
                            <span class="bi bi-backspace" style="color:red"></span>
                        </a>
                    </div>
                    <input asp-for="Fields[i].Value" class="form-control" />
                </div>
            }
        }
    }
</div>
<div>
    <a class="btn btn-default CreateField" data-toggle="tooltip" title="Add new fields" onclick="createField()">
        <span class="bi bi-plus-square"></span> Add new fields
    </a>
</div>

ToDoAspNetMvc/Views/Shared/_ToDoListDetails.cshtml
@model ToDoListLibrary.ToDoList

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="form-group">
    <label asp-for="Title" class="control-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title" class="text-danger"></span>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="Hide" /> @Html.DisplayNameFor(model => model.Hide)
    </label>
</div>
<div class="form-group">
    <input type="submit" value="Save" class="btn btn-primary" />
</div>