ToDoAspNetMvc/Controllers/ToDoEntriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using ToDoAspNetMvc.Models;
using ToDoListLibrary;

namespace ToDoAspNetMvc.Controllers;

public class ToDoEntriesController : Controller
{
    private readonly ApplicationContext _context;
    private readonly IMapper _mapper;

    public ToDoEntriesController(ApplicationContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    // GET: ToDoEntries
    public async Task<IActionResult> Index(string compare = null)
    {
        switch (compare)
        {
            case "equals":
                return View(await _context.Entities
            .Where(e => e.DueDate.Date == DateTime.Today)
            .ToListAsync());
            case "less":
                return View(await _context.Entities
            .Where(e => e.DueDate.Date < DateTime.Today)
            .ToListAsync());
            default:
                return View(await _context.Entities
            .ToListAsync());
        }
    }

    // GET: ToDoEntries/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoEntry = await _context.Entities
            .Include(l => l.Fields)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoEntry == null)
        {
            return NotFound();
        }

        return View(toDoEntry);
    }

    // GET: ToDoEntries/Create
    public IActionResult Create(int? owner)
    {
        ViewBag.Owner = owner;
        return View();
    }

    // POST: ToDoEntries/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("OwnerId,Id,Title,Description,DueDate,Completed,Fields")] ToDoEntryViewModel vm)
    {
        if (ModelState.IsValid)
        {
            var toDoEntry = _mapper.Map<ToDoEntry>(vm);
            toDoEntry.CreatedOn = DateTime.Now;
            _context.Add(toDoEntry);
            foreach (var field in vm.Fields)
            {
                var entityField = _mapper.Map<CustomField>(field);
                entityField.ToDoEntryId = toDoEntry.Id;
                _context.Add(entityField);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), "ToDoLists", new { id = toDoEntry.OwnerId });
        }
        return View(vm);
    }

    // GET: ToDoEntries/Create
    public async Task<IActionResult> CreateCopy(int? initial)
    {
        if (initial == null)
        {
            return NotFound();
        }

        var toDoEntry = await _context.Entities.Include(l => l.Fields).FirstOrDefaultAsync(e => e.Id == initial);
        if (toDoEntry == null)
        {
            return NotFound();
        }
        var todolists = await _context.Lists.ToListAsync();
        var vm = _mapper.Map<ToDoEntryViewModel>(toDoEntry);
        vm.ToDoLists = todolists.Select(l => new SelectListItem { Text = l.Title, Value = l.Id.ToString() }).ToList();
        return View(vm);
    }

    // POST: ToDoEntries/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateCopy([Bind("OwnerId,Title,Description,DueDate,Completed,Fields")] ToDoEntryViewModel vm)
    {
        if (ModelState.IsValid)
        {
            var toDoEntry = _mapper.Map<ToDoEntry>(vm);
            toDoEntry.CreatedOn = DateTime.Now;
            _context.Add(toDoEntry);
            foreach (var field in vm.Fields)
            {
                var entityField = _mapper.Map<CustomField>(field);
                toDoEntry.Fields.Add(entityField);
                _context.Add(entityField);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), "ToDoLists", new { id = toDoEntry.OwnerId });
        }
        return View(vm);
    }

    // GET: ToDoEntries/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoEntry = await _context.Entities.Include(l => l.Fields).FirstOrDefaultAsync(e => e.Id == id);
        if (toDoEntry == null)
        {
            return NotFound();
        }
        var vm = _mapper.Map<ToDoEntryViewModel>(toDoEntry);
        return View(vm);
    }

    // POST: ToDoEntries/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("OwnerId,Id,Title,Description,DueDate,Completed,Fields")] ToDoEntryViewModel vm)
    {
        var toDoEntry = await _context.Entities.Include(l => l.Fields).FirstOrDefaultAsync(e => e.Id == id);
        if (toDoEntry == null)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _mapper.Map(vm, toDoEntry);

                foreach (var modelField in vm.Fields)
                {
                    var existingField = toDoEntry.Fields.Where(f => f.Id == modelField.Id && f.Id != default)
                        .FirstOrDefault();
                    if (existingField != null)
                    {
                        _mapper.Map(modelField, existingField);
                    }
                    else
                    {
                        var newField = _mapper.Map<CustomField>(modelField);
                        newField.ToDoEntryId = id;
                        _context.Add(newField);
                    }
                }
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ToDoEntryExists(toDoEntry.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Details), "ToDoLists", new { id = toDoEntry.OwnerId });
        }
        return View(vm);
    }

    // GET: ToDoEntries/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoEntry = await _context.Entities
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoEntry == null)
        {
            return NotFound();
        }

        return View(toDoEntry);
    }

    // POST: ToDoEntries/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var toDoEntry = await _context.Entities.FindAsync(id);
        var ownerId = toDoEntry.OwnerId;
        _context.Entities.Remove(toDoEntry);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Details), "ToDoLists", new { id = ownerId });
    }

    public async Task<IActionResult> MarkCompleted(int id)
    {
        var toDoEntry = await _context.Entities.FindAsync(id);
        if (toDoEntry == null)
        {
            return NotFound();
        }
        var vm = new MarkCompletedViewModel { Id = toDoEntry.Id, Title = toDoEntry.Title, IsCompleted = toDoEntry.Completed == Status.Completed };
        return View(vm);
    }

    [HttpPost, ActionName("MarkCompleted")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> MarkCompletedConfirmed(int id, [Bind("Id,IsCompleted")] MarkCompletedViewModel vm)
    {
        var toDoEntry = await _context.Entities.FindAsync(id);
        if (ModelState.IsValid)
        {
            toDoEntry.Completed = vm.IsCompleted ? Status.Completed : Status.InProgress; 
            await _context.SaveChangesAsync();
            if (toDoEntry == null)
            {
                return NotFound();
            }
        }

        return View(vm);
    }

    private bool ToDoEntryExists(int id)
    {
        return _context.Entities.Any(e => e.Id == id);
    }
}

ToDoAspNetMvc/Controllers/ToDoListsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using ToDoListLibrary;

namespace ToDoAspNetMvc.Controllers;

public class ToDoListsController : Controller
{
    private readonly ApplicationContext _context;

    public ToDoListsController(ApplicationContext context)
    {
        _context = context;
    }

    // GET: ToDoLists
    public async Task<IActionResult> Index()
    {
        return View(await _context.Lists
            .Include(l => l.EntryList)
            .ToListAsync());
    }

    // GET: ToDoLists/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists
            .Include(l => l.EntryList)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoList == null)
        {
            return NotFound();
        }

        return View(toDoList);
    }

    // GET: ToDoLists/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: ToDoLists/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Title,Hide")] ToDoList toDoList)
    {
        if (ModelState.IsValid)
        {
            _context.Add(toDoList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(toDoList);
    }

    // GET: ToDoLists/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists.FindAsync(id);
        if (toDoList == null)
        {
            return NotFound();
        }
        return View(toDoList);
    }

    // POST: ToDoLists/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Hide")] ToDoList toDoList)
    {
        if (id != toDoList.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(toDoList);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ToDoListExists(toDoList.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(toDoList);
    }

    // GET: ToDoLists/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var toDoList = await _context.Lists
            .FirstOrDefaultAsync(m => m.Id == id);
        if (toDoList == null)
        {
            return NotFound();
        }

        return View(toDoList);
    }

    // POST: ToDoLists/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var toDoList = await _context.Lists.FindAsync(id);
        _context.Lists.Remove(toDoList);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool ToDoListExists(int id)
    {
        return _context.Lists.Any(e => e.Id == id);
    }
}

ToDoAspNetMvc/Views/ToDoLists/Create.cshtml
@model ToDoListLibrary.ToDoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <partial name="_ToDoListDetails" />
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default btn-lg" asp-action="Index" >
        <span class="bi bi-arrow-left"></span>Back to Lists
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoAspNetMvc/Views/ToDoLists/Delete.cshtml
@model ToDoListLibrary.ToDoList

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hide)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hide)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">
            <span class="bi bi-arrow-left"></span>Back to List
        </a>
    </form>
</div>

ToDoAspNetMvc/Views/ToDoLists/Details.cshtml
@model ToDoListLibrary.ToDoList

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Title)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hide)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hide)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-default btn-lg" asp-action="Edit" asp-route-id="@Model.Id">
        <span class="bi bi-pencil"></span>
    </a> |
    <a class="btn btn-default btn-lg" asp-action="Index">
        <span class="bi bi-arrow-left"></span>Back to Lists
        </a>
</div>

<div class="form-check form-switch">
    <label class="form-check-label" for="ShowCompleted">Show completed</label>
    @Html.CheckBox("ShowCompleted", new { id = "ShowCompleted", @class = "form-check-input" })
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Due Date
            </th>
            <th>
                Completed
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.EntryList)
        {
            <tr onclick="location.href='@(Url.Action("Details", "ToDoEntries", new { id=item.Id }))'"
                class="@(item.Completed == ToDoListLibrary.Status.Completed ? "row-to-hide" : "")" style="@(item.Completed == ToDoListLibrary.Status.Completed ? "display:none" : "")">
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Completed)
                </td>
                <td>
                    <a class="btn btn-default btn-lg" asp-controller="ToDoEntries" asp-action="Delete" asp-route-id="@item.Id" data-toggle="tooltip" title="Delete">
                        <span class="bi bi-trash"></span>
                    </a> |
                    <a class="btn btn-default btn-lg" asp-controller="ToDoEntries" asp-action="CreateCopy" asp-route-initial="@item.Id" data-toggle="tooltip" title="Copy">
                        <span class="bi bi-copy"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-default btn-lg" asp-controller="ToDoEntries" asp-action="Create" asp-route-owner="@(Model.Id)">
        <span class="bi bi-plus-circle"></span>New Item
    </a>
</div>

@section Scripts
{
    <script>
        $(function () {
            $('#ShowCompleted').change(function () {
                var hiddenRows = document.getElementsByClassName("row-to-hide");
                for (var i = 0; i < hiddenRows.length; i++) {
                    if (document.getElementById('ShowCompleted').checked) {
                        hiddenRows[i].style.display = "";
                    } else {
                        hiddenRows[i].style.display = "none";
                    }
                }
            });
        });
    </script>
}

ToDoAspNetMvc/Views/ToDoLists/Edit.cshtml
@model ToDoListLibrary.ToDoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            <partial name="_ToDoListDetails" />
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default btn-lg" asp-action="Details" asp-route-id="@Model.Id">
        <span class="bi bi-arrow-left"></span>Back to List
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoAspNetMvc/Views/ToDoLists/Index.cshtml
@model IEnumerable<ToDoListLibrary.ToDoList>

@{
    ViewData["Title"] = "Index";
}

<dib class="card shadow border-0 mt-4">
    <div class="card header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1>
                    To Do Lists
                </h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6"></div>
            <div class="col-6 text-end">
                <a class="btn btn-default btn-lg" asp-action="Create">
                    <span class="bi bi-plus-circle"></span> Create new List
                </a>
            </div>
        </div>
    </div>
</dib>
<div class="form-check form-switch">
    <label class="form-check-label" for="ShowHidden">Show hidden lists</label>
    @Html.CheckBox("ShowHidden", new { id = "ShowHidden", @class = "form-check-input" })
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hide)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="@(item.Hide ? "row-to-hide" : "")" style="@(item.Hide ? "display:none" : "")" onclick="location.href='@(Url.Action("Details", "ToDoLists", new { id=item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hide)
                </td>
                <td>
                    <a class="btn btn-default btn-lg" asp-action="Delete" asp-route-id="@item.Id" data-toggle="tooltip" title="Delete">
                        <span class="bi bi-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts
{
    <script>
        $(function () {
            $('#ShowHidden').change(function () {
                var hiddenRows = document.getElementsByClassName("row-to-hide");
                for (var i = 0; i < hiddenRows.length; i++) {
                    if (document.getElementById('ShowHidden').checked) {
                        hiddenRows[i].style.display = "";
                    } else {
                        hiddenRows[i].style.display = "none";
                    }
                }
            });
        });
    </script>
}